locations = ["China" , "South Korea" , "Japan" , "New York" , "Greece"]
print("Original Order:")
print(locations)
print("Alphabetical:")
print(sorted(locations))
print("Original Order:")
print(locations)
print("Reverse Alphabetical:")
print(sorted(locations, reverse=True))
print("Original Order:")
print(locations)
print("Reversed:")
locations.reverse()
print("Original Order:")
locations.reverse()
print(locations)
print("Alphabetical")
locations.sort()
print(locations)
print("Reverse alphabetical")
locations.sort(reverse=True)
print(locations)